/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArticleTypeDetails model module.
 * @module model/ArticleTypeDetails
 * @version 2.0.0
 */
class ArticleTypeDetails {
    /**
     * Constructs a new <code>ArticleTypeDetails</code>.
     * @alias module:model/ArticleTypeDetails
     * @param title {String} 
     */
    constructor(title) { 
        
        ArticleTypeDetails.initialize(this, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title) { 
        obj['title'] = title;
    }

    /**
     * Constructs a <code>ArticleTypeDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArticleTypeDetails} obj Optional instance to populate.
     * @return {module:model/ArticleTypeDetails} The populated <code>ArticleTypeDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArticleTypeDetails();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
ArticleTypeDetails.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ArticleTypeDetails.prototype['description'] = undefined;






export default ArticleTypeDetails;

