/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.BlockShortcodeError = factory(root.Lettera.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The BlockShortcodeError model module.
   * @module model/BlockShortcodeError
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BlockShortcodeError</code>.
   * @alias module:model/BlockShortcodeError
   * @class
   * @param errorMessage {String} 
   * @param content {String} 
   */
  var exports = function(errorMessage, content) {
    var _this = this;

    _this['errorMessage'] = errorMessage;
    _this['content'] = content;
  };

  /**
   * Constructs a <code>BlockShortcodeError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BlockShortcodeError} obj Optional instance to populate.
   * @return {module:model/BlockShortcodeError} The populated <code>BlockShortcodeError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;
  /**
   * @member {String} content
   */
  exports.prototype['content'] = undefined;



  return exports;
}));


