/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockShortcodeError from './BlockShortcodeError';
import FactInfo from './FactInfo';
import ImageInfo from './ImageInfo';

/**
 * The Block model module.
 * @module model/Block
 * @version 1.0.0
 */
class Block {
    /**
     * Constructs a new <code>Block</code>.
     * @alias module:model/Block
     */
    constructor() { 
        
        Block.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Block</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Block} obj Optional instance to populate.
     * @return {module:model/Block} The populated <code>Block</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Block();

            if (data.hasOwnProperty('paragraph')) {
                obj['paragraph'] = ApiClient.convertToType(data['paragraph'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ImageInfo.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('factBox')) {
                obj['factBox'] = FactInfo.constructFromObject(data['factBox']);
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('shortcodeError')) {
                obj['shortcodeError'] = BlockShortcodeError.constructFromObject(data['shortcodeError']);
            }
            if (data.hasOwnProperty('embed')) {
                obj['embed'] = ApiClient.convertToType(data['embed'], [Object]);
            }
            if (data.hasOwnProperty('instagramEmbed')) {
                obj['instagramEmbed'] = ApiClient.convertToType(data['instagramEmbed'], 'String');
            }
            if (data.hasOwnProperty('infogramEmbed')) {
                obj['infogramEmbed'] = ApiClient.convertToType(data['infogramEmbed'], [Object]);
            }
            if (data.hasOwnProperty('twitterEmbed')) {
                obj['twitterEmbed'] = ApiClient.convertToType(data['twitterEmbed'], 'String');
            }
            if (data.hasOwnProperty('facebookEmbed')) {
                obj['facebookEmbed'] = ApiClient.convertToType(data['facebookEmbed'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} paragraph
 */
Block.prototype['paragraph'] = undefined;

/**
 * @member {String} html
 */
Block.prototype['html'] = undefined;

/**
 * @member {module:model/ImageInfo} image
 */
Block.prototype['image'] = undefined;

/**
 * @member {module:model/FactInfo} factBox
 */
Block.prototype['factBox'] = undefined;

/**
 * @member {String} headline
 */
Block.prototype['headline'] = undefined;

/**
 * @member {module:model/BlockShortcodeError} shortcodeError
 */
Block.prototype['shortcodeError'] = undefined;

/**
 * @member {Array.<Object>} embed
 */
Block.prototype['embed'] = undefined;

/**
 * @member {String} instagramEmbed
 */
Block.prototype['instagramEmbed'] = undefined;

/**
 * @member {Array.<Object>} infogramEmbed
 */
Block.prototype['infogramEmbed'] = undefined;

/**
 * @member {String} twitterEmbed
 */
Block.prototype['twitterEmbed'] = undefined;

/**
 * @member {String} facebookEmbed
 */
Block.prototype['facebookEmbed'] = undefined;






export default Block;

