/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockShortcodeError model module.
 * @module model/BlockShortcodeError
 * @version 1.0.0
 */
class BlockShortcodeError {
    /**
     * Constructs a new <code>BlockShortcodeError</code>.
     * @alias module:model/BlockShortcodeError
     * @param errorMessage {String} 
     * @param content {String} 
     */
    constructor(errorMessage, content) { 
        
        BlockShortcodeError.initialize(this, errorMessage, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, errorMessage, content) { 
        obj['errorMessage'] = errorMessage;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>BlockShortcodeError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockShortcodeError} obj Optional instance to populate.
     * @return {module:model/BlockShortcodeError} The populated <code>BlockShortcodeError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockShortcodeError();

            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} errorMessage
 */
BlockShortcodeError.prototype['errorMessage'] = undefined;

/**
 * @member {String} content
 */
BlockShortcodeError.prototype['content'] = undefined;






export default BlockShortcodeError;

