/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoxInfo', 'model/ImageInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BoxInfo'), require('./ImageInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.Block = factory(root.Lettera.ApiClient, root.Lettera.BoxInfo, root.Lettera.ImageInfo);
  }
}(this, function(ApiClient, BoxInfo, ImageInfo) {
  'use strict';



  /**
   * The Block model module.
   * @module model/Block
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Block</code>.
   * @alias module:model/Block
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Block</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Block} obj Optional instance to populate.
   * @return {module:model/Block} The populated <code>Block</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('paragraph')) {
        obj['paragraph'] = ApiClient.convertToType(data['paragraph'], 'String');
      }
      if (data.hasOwnProperty('html')) {
        obj['html'] = ApiClient.convertToType(data['html'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ImageInfo.constructFromObject(data['image']);
      }
      if (data.hasOwnProperty('box')) {
        obj['box'] = BoxInfo.constructFromObject(data['box']);
      }
      if (data.hasOwnProperty('headline')) {
        obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
      }
      if (data.hasOwnProperty('footnote')) {
        obj['footnote'] = ApiClient.convertToType(data['footnote'], 'String');
      }
      if (data.hasOwnProperty('question')) {
        obj['question'] = ApiClient.convertToType(data['question'], 'String');
      }
      if (data.hasOwnProperty('quote')) {
        obj['quote'] = ApiClient.convertToType(data['quote'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} paragraph
   */
  exports.prototype['paragraph'] = undefined;
  /**
   * @member {String} html
   */
  exports.prototype['html'] = undefined;
  /**
   * @member {module:model/ImageInfo} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {module:model/BoxInfo} box
   */
  exports.prototype['box'] = undefined;
  /**
   * @member {String} headline
   */
  exports.prototype['headline'] = undefined;
  /**
   * @member {String} footnote
   */
  exports.prototype['footnote'] = undefined;
  /**
   * @member {String} question
   */
  exports.prototype['question'] = undefined;
  /**
   * @member {String} quote
   */
  exports.prototype['quote'] = undefined;



  return exports;
}));


