/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoxType from './BoxType';

/**
 * The BoxInfo model module.
 * @module model/BoxInfo
 * @version 2.0.0
 */
class BoxInfo {
    /**
     * Constructs a new <code>BoxInfo</code>.
     * @alias module:model/BoxInfo
     * @param title {String} 
     * @param content {Array.<String>} 
     * @param type {module:model/BoxType} 
     */
    constructor(title, content, type) { 
        
        BoxInfo.initialize(this, title, content, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, content, type) { 
        obj['title'] = title;
        obj['content'] = content;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>BoxInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoxInfo} obj Optional instance to populate.
     * @return {module:model/BoxInfo} The populated <code>BoxInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BoxInfo();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = BoxType.constructFromObject(data['type']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
BoxInfo.prototype['title'] = undefined;

/**
 * @member {String} headline
 */
BoxInfo.prototype['headline'] = undefined;

/**
 * @member {Array.<String>} content
 */
BoxInfo.prototype['content'] = undefined;

/**
 * @member {module:model/BoxType} type
 */
BoxInfo.prototype['type'] = undefined;






export default BoxInfo;

