/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoxType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BoxType'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.BoxInfo = factory(root.Lettera.ApiClient, root.Lettera.BoxType);
  }
}(this, function(ApiClient, BoxType) {
  'use strict';



  /**
   * The BoxInfo model module.
   * @module model/BoxInfo
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>BoxInfo</code>.
   * @alias module:model/BoxInfo
   * @class
   * @param title {String} 
   * @param content {Array.<String>} 
   * @param type {module:model/BoxType} 
   */
  var exports = function(title, content, type) {
    var _this = this;

    _this['title'] = title;
    _this['content'] = content;
    _this['type'] = type;
  };

  /**
   * Constructs a <code>BoxInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoxInfo} obj Optional instance to populate.
   * @return {module:model/BoxInfo} The populated <code>BoxInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('headline')) {
        obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], ['String']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = BoxType.constructFromObject(data['type']);
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} headline
   */
  exports.prototype['headline'] = undefined;
  /**
   * @member {Array.<String>} content
   */
  exports.prototype['content'] = undefined;
  /**
   * @member {module:model/BoxType} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


