/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BoxType.
* @enum {}
* @readonly
*/
export default class BoxType {
    
        /**
         * value: "fact"
         * @const
         */
        "fact" = "fact";

    
        /**
         * value: "review"
         * @const
         */
        "review" = "review";

    

    /**
    * Returns a <code>BoxType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BoxType} The enum <code>BoxType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

