/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategoryHierarchy model module.
 * @module model/CategoryHierarchy
 * @version 1.0.0
 */
class CategoryHierarchy {
    /**
     * Constructs a new <code>CategoryHierarchy</code>.
     * @alias module:model/CategoryHierarchy
     * @param name {String} 
     * @param subcategories {Array.<String>} 
     */
    constructor(name, subcategories) { 
        
        CategoryHierarchy.initialize(this, name, subcategories);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, subcategories) { 
        obj['name'] = name;
        obj['subcategories'] = subcategories;
    }

    /**
     * Constructs a <code>CategoryHierarchy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryHierarchy} obj Optional instance to populate.
     * @return {module:model/CategoryHierarchy} The populated <code>CategoryHierarchy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryHierarchy();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('subcategories')) {
                obj['subcategories'] = ApiClient.convertToType(data['subcategories'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CategoryHierarchy.prototype['name'] = undefined;

/**
 * @member {Array.<String>} subcategories
 */
CategoryHierarchy.prototype['subcategories'] = undefined;






export default CategoryHierarchy;

