/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Category.
* @enum {}
* @readonly
*/
export default class Category {
    
        /**
         * value: "Framsidan"
         * @const
         */
        "Framsidan" = "Framsidan";

    
        /**
         * value: "Nyheter"
         * @const
         */
        "Nyheter" = "Nyheter";

    
        /**
         * value: "Ekonomi"
         * @const
         */
        "Ekonomi" = "Ekonomi";

    
        /**
         * value: "NordenOchVarlden"
         * @const
         */
        "NordenOchVarlden" = "NordenOchVarlden";

    
        /**
         * value: "Finland"
         * @const
         */
        "Finland" = "Finland";

    
        /**
         * value: "KlimatOchMiljo"
         * @const
         */
        "KlimatOchMiljo" = "KlimatOchMiljo";

    
        /**
         * value: "Kultur"
         * @const
         */
        "Kultur" = "Kultur";

    
        /**
         * value: "Litteratur"
         * @const
         */
        "Litteratur" = "Litteratur";

    
        /**
         * value: "Musik"
         * @const
         */
        "Musik" = "Musik";

    
        /**
         * value: "Scen"
         * @const
         */
        "Scen" = "Scen";

    
        /**
         * value: "Konst"
         * @const
         */
        "Konst" = "Konst";

    
        /**
         * value: "FilmOchTv"
         * @const
         */
        "FilmOchTv" = "FilmOchTv";

    
        /**
         * value: "Opinion"
         * @const
         */
        "Opinion" = "Opinion";

    
        /**
         * value: "Ledare"
         * @const
         */
        "Ledare" = "Ledare";

    
        /**
         * value: "Kolumner"
         * @const
         */
        "Kolumner" = "Kolumner";

    
        /**
         * value: "Debatt"
         * @const
         */
        "Debatt" = "Debatt";

    
        /**
         * value: "Kronikor"
         * @const
         */
        "Kronikor" = "Kronikor";

    
        /**
         * value: "Sport"
         * @const
         */
        "Sport" = "Sport";

    
        /**
         * value: "Handboll"
         * @const
         */
        "Handboll" = "Handboll";

    
        /**
         * value: "Fotboll"
         * @const
         */
        "Fotboll" = "Fotboll";

    
        /**
         * value: "Ishockey"
         * @const
         */
        "Ishockey" = "Ishockey";

    
        /**
         * value: "Motorsport"
         * @const
         */
        "Motorsport" = "Motorsport";

    
        /**
         * value: "Friidrott"
         * @const
         */
        "Friidrott" = "Friidrott";

    
        /**
         * value: "Skidsport"
         * @const
         */
        "Skidsport" = "Skidsport";

    
        /**
         * value: "Livsstil"
         * @const
         */
        "Livsstil" = "Livsstil";

    
        /**
         * value: "MedicinOchHalsa"
         * @const
         */
        "MedicinOchHalsa" = "MedicinOchHalsa";

    
        /**
         * value: "FamiljOchRelationer"
         * @const
         */
        "FamiljOchRelationer" = "FamiljOchRelationer";

    
        /**
         * value: "MatOchDryck"
         * @const
         */
        "MatOchDryck" = "MatOchDryck";

    
        /**
         * value: "Resor"
         * @const
         */
        "Resor" = "Resor";

    
        /**
         * value: "BilarOchFordon"
         * @const
         */
        "BilarOchFordon" = "BilarOchFordon";

    
        /**
         * value: "HemOchTradgard"
         * @const
         */
        "HemOchTradgard" = "HemOchTradgard";

    

    /**
    * Returns a <code>Category</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Category} The enum <code>Category</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

