/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FactInfo model module.
 * @module model/FactInfo
 * @version 2.0.0
 */
class FactInfo {
    /**
     * Constructs a new <code>FactInfo</code>.
     * @alias module:model/FactInfo
     * @param title {String} 
     * @param content {Array.<String>} 
     */
    constructor(title, content) { 
        
        FactInfo.initialize(this, title, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, content) { 
        obj['title'] = title;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>FactInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FactInfo} obj Optional instance to populate.
     * @return {module:model/FactInfo} The populated <code>FactInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FactInfo();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
FactInfo.prototype['title'] = undefined;

/**
 * @member {Array.<String>} content
 */
FactInfo.prototype['content'] = undefined;






export default FactInfo;

