/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.FactInfo = factory(root.Lettera.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The FactInfo model module.
   * @module model/FactInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FactInfo</code>.
   * @alias module:model/FactInfo
   * @class
   * @param factTitle {String} 
   * @param factContent {Array.<String>} 
   */
  var exports = function(factTitle, factContent) {
    var _this = this;

    _this['factTitle'] = factTitle;
    _this['factContent'] = factContent;
  };

  /**
   * Constructs a <code>FactInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FactInfo} obj Optional instance to populate.
   * @return {module:model/FactInfo} The populated <code>FactInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('factTitle')) {
        obj['factTitle'] = ApiClient.convertToType(data['factTitle'], 'String');
      }
      if (data.hasOwnProperty('factContent')) {
        obj['factContent'] = ApiClient.convertToType(data['factContent'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} factTitle
   */
  exports.prototype['factTitle'] = undefined;
  /**
   * @member {Array.<String>} factContent
   */
  exports.prototype['factContent'] = undefined;



  return exports;
}));


