/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Alignment from './Alignment';

/**
 * The ImageInfo model module.
 * @module model/ImageInfo
 * @version 1.0.0
 */
class ImageInfo {
    /**
     * Constructs a new <code>ImageInfo</code>.
     * @alias module:model/ImageInfo
     * @param url {String} 
     * @param thumb {String} 
     */
    constructor(url, thumb) { 
        
        ImageInfo.initialize(this, url, thumb);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, thumb) { 
        obj['url'] = url;
        obj['thumb'] = thumb;
    }

    /**
     * Constructs a <code>ImageInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageInfo} obj Optional instance to populate.
     * @return {module:model/ImageInfo} The populated <code>ImageInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageInfo();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('caption')) {
                obj['caption'] = ApiClient.convertToType(data['caption'], 'String');
            }
            if (data.hasOwnProperty('alignment')) {
                obj['alignment'] = Alignment.constructFromObject(data['alignment']);
            }
            if (data.hasOwnProperty('byline')) {
                obj['byline'] = ApiClient.convertToType(data['byline'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
ImageInfo.prototype['url'] = undefined;

/**
 * @member {String} thumb
 */
ImageInfo.prototype['thumb'] = undefined;

/**
 * @member {String} caption
 */
ImageInfo.prototype['caption'] = undefined;

/**
 * @member {module:model/Alignment} alignment
 */
ImageInfo.prototype['alignment'] = undefined;

/**
 * @member {String} byline
 */
ImageInfo.prototype['byline'] = undefined;






export default ImageInfo;

