/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventType'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.Notification = factory(root.Lettera.ApiClient, root.Lettera.EventType);
  }
}(this, function(ApiClient, EventType) {
  'use strict';



  /**
   * The Notification model module.
   * @module model/Notification
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @class
   * @param contentType {String} 
   * @param eventtype {module:model/EventType} 
   * @param uuid {String} 
   */
  var exports = function(contentType, eventtype, uuid) {
    var _this = this;

    _this['contentType'] = contentType;
    _this['eventtype'] = eventtype;
    _this['uuid'] = uuid;
  };

  /**
   * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notification} obj Optional instance to populate.
   * @return {module:model/Notification} The populated <code>Notification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contentType')) {
        obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
      }
      if (data.hasOwnProperty('eventid')) {
        obj['eventid'] = ApiClient.convertToType(data['eventid'], 'Number');
      }
      if (data.hasOwnProperty('eventtype')) {
        obj['eventtype'] = EventType.constructFromObject(data['eventtype']);
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} contentType
   */
  exports.prototype['contentType'] = undefined;
  /**
   * @member {Number} eventid
   */
  exports.prototype['eventid'] = undefined;
  /**
   * @member {module:model/EventType} eventtype
   */
  exports.prototype['eventtype'] = undefined;
  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;



  return exports;
}));


