/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Paper.
* @enum {}
* @readonly
*/
export default class Paper {
    
        /**
         * value: "hbl"
         * @const
         */
        "hbl" = "hbl";

    
        /**
         * value: "ht"
         * @const
         */
        "ht" = "ht";

    
        /**
         * value: "vn"
         * @const
         */
        "vn" = "vn";

    
        /**
         * value: "on"
         * @const
         */
        "on" = "on";

    

    /**
    * Returns a <code>Paper</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Paper} The enum <code>Paper</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

