/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ImageInfo from './ImageInfo';

/**
 * The RelatedArticle model module.
 * @module model/RelatedArticle
 * @version 1.0.0
 */
class RelatedArticle {
    /**
     * Constructs a new <code>RelatedArticle</code>.
     * @alias module:model/RelatedArticle
     * @param uuid {String} 
     * @param title {String} 
     * @param publishingTime {String} 
     * @param premium {Boolean} 
     */
    constructor(uuid, title, publishingTime, premium) { 
        
        RelatedArticle.initialize(this, uuid, title, publishingTime, premium);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, title, publishingTime, premium) { 
        obj['uuid'] = uuid;
        obj['title'] = title;
        obj['publishingTime'] = publishingTime;
        obj['premium'] = premium;
    }

    /**
     * Constructs a <code>RelatedArticle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelatedArticle} obj Optional instance to populate.
     * @return {module:model/RelatedArticle} The populated <code>RelatedArticle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelatedArticle();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('preamble')) {
                obj['preamble'] = ApiClient.convertToType(data['preamble'], 'String');
            }
            if (data.hasOwnProperty('listImage')) {
                obj['listImage'] = ImageInfo.constructFromObject(data['listImage']);
            }
            if (data.hasOwnProperty('publishingTime')) {
                obj['publishingTime'] = ApiClient.convertToType(data['publishingTime'], 'String');
            }
            if (data.hasOwnProperty('premium')) {
                obj['premium'] = ApiClient.convertToType(data['premium'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
RelatedArticle.prototype['uuid'] = undefined;

/**
 * @member {String} title
 */
RelatedArticle.prototype['title'] = undefined;

/**
 * @member {String} preamble
 */
RelatedArticle.prototype['preamble'] = undefined;

/**
 * @member {module:model/ImageInfo} listImage
 */
RelatedArticle.prototype['listImage'] = undefined;

/**
 * @member {String} publishingTime
 */
RelatedArticle.prototype['publishingTime'] = undefined;

/**
 * @member {Boolean} premium
 */
RelatedArticle.prototype['premium'] = undefined;






export default RelatedArticle;

