/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Lettera) {
      root.Lettera = {};
    }
    root.Lettera.Scoring = factory(root.Lettera.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Scoring model module.
   * @module model/Scoring
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Scoring</code>.
   * @alias module:model/Scoring
   * @class
   * @param cutoffPriority {Array.<Array.<Object>>} 
   * @param cutoffTimeOnSite {Array.<Array.<Object>>} 
   */
  var exports = function(cutoffPriority, cutoffTimeOnSite) {
    var _this = this;

    _this['cutoffPriority'] = cutoffPriority;
    _this['cutoffTimeOnSite'] = cutoffTimeOnSite;
  };

  /**
   * Constructs a <code>Scoring</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scoring} obj Optional instance to populate.
   * @return {module:model/Scoring} The populated <code>Scoring</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cutoffPriority')) {
        obj['cutoffPriority'] = ApiClient.convertToType(data['cutoffPriority'], [[Object]]);
      }
      if (data.hasOwnProperty('cutoffTimeOnSite')) {
        obj['cutoffTimeOnSite'] = ApiClient.convertToType(data['cutoffTimeOnSite'], [[Object]]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Array.<Object>>} cutoffPriority
   */
  exports.prototype['cutoffPriority'] = undefined;
  /**
   * @member {Array.<Array.<Object>>} cutoffTimeOnSite
   */
  exports.prototype['cutoffTimeOnSite'] = undefined;



  return exports;
}));


