/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Lettera);
  }
}(this, function(expect, Lettera) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Lettera.ArticleStub();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticleStub', function() {
    it('should create an instance of ArticleStub', function() {
      // uncomment below and update the code to test ArticleStub
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be.a(Lettera.ArticleStub);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property articleTitle (base name: "articleTitle")', function() {
      // uncomment below and update the code to test the property articleTitle
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property authors (base name: "authors")', function() {
      // uncomment below and update the code to test the property authors
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property preamble (base name: "preamble")', function() {
      // uncomment below and update the code to test the property preamble
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property mainImage (base name: "mainImage")', function() {
      // uncomment below and update the code to test the property mainImage
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property listImage (base name: "listImage")', function() {
      // uncomment below and update the code to test the property listImage
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property premium (base name: "premium")', function() {
      // uncomment below and update the code to test the property premium
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property publishingTime (base name: "publishingTime")', function() {
      // uncomment below and update the code to test the property publishingTime
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "updateTime")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property relatedArticles (base name: "relatedArticles")', function() {
      // uncomment below and update the code to test the property relatedArticles
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property articleType (base name: "articleType")', function() {
      // uncomment below and update the code to test the property articleType
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property articleTypeDetails (base name: "articleTypeDetails")', function() {
      // uncomment below and update the code to test the property articleTypeDetails
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property paper (base name: "paper")', function() {
      // uncomment below and update the code to test the property paper
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property shareUrl (base name: "shareUrl")', function() {
      // uncomment below and update the code to test the property shareUrl
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property liveReporting (base name: "liveReporting")', function() {
      // uncomment below and update the code to test the property liveReporting
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

    it('should have the property articlePriority (base name: "articlePriority")', function() {
      // uncomment below and update the code to test the property articlePriority
      //var instance = new Lettera.ArticleStub();
      //expect(instance).to.be();
    });

  });

}));
