/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Alignment', 'model/Article', 'model/ArticleStub', 'model/ArticleType', 'model/ArticleTypeDetails', 'model/Author', 'model/Block', 'model/BoxInfo', 'model/BoxType', 'model/Category', 'model/Cutoff', 'model/ImageInfo', 'model/Paper', 'model/Scoring', 'api/ArticlesApi', 'api/CategoriesApi', 'api/ListsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Alignment'), require('./model/Article'), require('./model/ArticleStub'), require('./model/ArticleType'), require('./model/ArticleTypeDetails'), require('./model/Author'), require('./model/Block'), require('./model/BoxInfo'), require('./model/BoxType'), require('./model/Category'), require('./model/Cutoff'), require('./model/ImageInfo'), require('./model/Paper'), require('./model/Scoring'), require('./api/ArticlesApi'), require('./api/CategoriesApi'), require('./api/ListsApi'));
  }
}(function(ApiClient, Alignment, Article, ArticleStub, ArticleType, ArticleTypeDetails, Author, Block, BoxInfo, BoxType, Category, Cutoff, ImageInfo, Paper, Scoring, ArticlesApi, CategoriesApi, ListsApi) {
  'use strict';

  /**
   * h2KSF_Medias_articles_service_h2Changelog_for_V3ulliUnified_codeListArticle_code_and_codeRelatedArticle_code_into_a_single_type_codeArticleStub_code__NOTE_In_contrast_to_the_old_types_codeArticleStub_relatedArticles_code_is_now_an_optional_value__liliAdded_endpoint_code_article_uuid_stub_code_liliRemoved_deprecated_endpoint_code_article_search_code_li_ul.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Lettera = require('index'); // See note below*.
   * var xxxSvc = new Lettera.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Lettera.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Lettera.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Lettera.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 3.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Alignment model constructor.
     * @property {module:model/Alignment}
     */
    Alignment: Alignment,
    /**
     * The Article model constructor.
     * @property {module:model/Article}
     */
    Article: Article,
    /**
     * The ArticleStub model constructor.
     * @property {module:model/ArticleStub}
     */
    ArticleStub: ArticleStub,
    /**
     * The ArticleType model constructor.
     * @property {module:model/ArticleType}
     */
    ArticleType: ArticleType,
    /**
     * The ArticleTypeDetails model constructor.
     * @property {module:model/ArticleTypeDetails}
     */
    ArticleTypeDetails: ArticleTypeDetails,
    /**
     * The Author model constructor.
     * @property {module:model/Author}
     */
    Author: Author,
    /**
     * The Block model constructor.
     * @property {module:model/Block}
     */
    Block: Block,
    /**
     * The BoxInfo model constructor.
     * @property {module:model/BoxInfo}
     */
    BoxInfo: BoxInfo,
    /**
     * The BoxType model constructor.
     * @property {module:model/BoxType}
     */
    BoxType: BoxType,
    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category: Category,
    /**
     * The Cutoff model constructor.
     * @property {module:model/Cutoff}
     */
    Cutoff: Cutoff,
    /**
     * The ImageInfo model constructor.
     * @property {module:model/ImageInfo}
     */
    ImageInfo: ImageInfo,
    /**
     * The Paper model constructor.
     * @property {module:model/Paper}
     */
    Paper: Paper,
    /**
     * The Scoring model constructor.
     * @property {module:model/Scoring}
     */
    Scoring: Scoring,
    /**
     * The ArticlesApi service constructor.
     * @property {module:api/ArticlesApi}
     */
    ArticlesApi: ArticlesApi,
    /**
     * The CategoriesApi service constructor.
     * @property {module:api/CategoriesApi}
     */
    CategoriesApi: CategoriesApi,
    /**
     * The ListsApi service constructor.
     * @property {module:api/ListsApi}
     */
    ListsApi: ListsApi
  };

  return exports;
}));
